package com.vx.dyvide.controller.restAPI.HERE;

public class HEREInfo {

    public static final String APP_ID = "CqC8HduNTxmoE5T51TpG";
    public static String APP_BEARER_TOKEN = "eyJhbGciOiJSUzUxMiIsImN0eSI6IkpXVCIsImlzcyI6IkhFUkUiLCJhaWQiOiJDcUM4SGR1TlR4bW9FNVQ1MVRwRyIsImlhdCI6MTU5MTAzOTU5NywiZXhwIjoxNTkxMTI1OTk3LCJraWQiOiJqMSJ9.ZXlKaGJHY2lPaUprYVhJaUxDSmxibU1pT2lKQk1qVTJRMEpETFVoVE5URXlJbjAuLm5ESG1IcTBLTWhFbGI4RXhZYTQwWncuOFhyQWo1M2daa25rTWtqQ1l5bkdXdUVsM3J3VkZnVmQ3enZWMXFKNWtsbUl1MUQzT0hEZGE2aXZOSnZ0Ny1vc1F2dnFWeGdaTGI1aFZhNlllTTQybk9uRG1zaFRLTkxrbGVleU1GWXg4cFNRSklrUzh6X2xDUVRSS1RhZUdNQnkubllQUUlyYXdVOEVGalB4VmlMVnhDNTBuQTZQQWNqd3Mzd1BsU1Y3WFRObw.bkHGQnRC-RvZwzfnudFbZjONdUg1a008xAIEoYsv6GFkmv66cHilO80dK2qvgoxnd1RHGonMeSir8kvVselTEWt7KRkohoj61vrLZ0C1YpQmEcwjPS3DzlS9TLsQ5BjOzHu1kSZBm97dyLfCdMg7Gn4on07ytJo6q0IAa0JTDP3u5r83uZno4lztokCdqcFGrgllIpHhFDmvjb0HUM5IfExhuaApqYwmKjiouJ1H_tBEIg8ytFg7jjirn2UUBGvEwZcRsq9og1XsyBNCZMAXD4TZ6cmDlGmufCFCWwUF11zi3P5TPmCMioECq8hm9LUcQhNBSePmRQNxHmS7v6oscA";
    public static final String API_KEY = "S9sOODt2k6XdqokbsrUDm-SIagLqkt5w-f1QN-cldM0";
    public static final String ACCESS_TOKEN = "Flia4oY0XXdo8EpqETwzhdRPzlSINb-NNrJ_a_yQCD41_VjlaLJsMQIEfRbnkjyWEcrDWbiGTbMsvvMH5_qzFw";
    public static final String APP_CODE = "SPgHJo2XnSyggCfnQ4aA";
}
